name: werather_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_glow: ^0.2.0
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.2
  location: ^4.3.0
  permission_handler: ^9.2.0
  geocoding: ^2.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_native_splash: ^2.1.1

flutter_native_splash:
  color: "#4E1043"
  image: assets/splash.png
  android: true
  ios: true


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
